services:
  app:
    build: .
    container_name: my_bot_app
    env_file: .env
    depends_on:
      - redis
    volumes:
      - .:/app
    
  redis:
    image: redis:7
    container_name: redis_container
    restart: always
    ports:
      - "6380:6379"

volumes:
  pgdata:
